name: Python Flask App
on:
  workflow_dispatch:
jobs:
  build_app:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6.0.2
      - name: docker login to acr  
        uses: docker/login-action@v3.6.0
        with: 
          registry: ${{ secrets.ACR_REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - name: build and push to acr
        uses: docker/build-push-action@v6.18.0
        with:
          context: python-flask-app/.
          push: true
          tags: ${{ secrets.ACR_REGISTRY }}/flask-app:${{ github.run_number }}
  deploy_aks:
    runs-on: ubuntu-latest
    needs: build_app
    steps:
    - name: login to azure
      uses: Azure/login@v2.3.0
      with:
        client-secret: $ {{ secrets.CLIENT_SECRET }}
        client-id: $ {{ secrets.CLIENT_ID }}
        tenant-id: $ {{ secrets.TENANT_ID }}
    - name: set aks context
      uses: azure/aks-set-context@v4
      with:
        resource-group: kml_rg_main-c4ed4574dea848c2
        cluster-name: myaks
    - name: deploy to aks
      uses: Azure/k8s-deploy@v5
      with:
        images: mypythonapprepo.azurecr.io/mypythonapprepo:${{ github.run_number }}
        manifests: deployment.yaml
        imagepullsecrets: acr-secret # k8s secret
          
        
        
        
      
        
      
