name: Python Flask App Deploy - OIDC
on:
  workflow_dispatch:
  workflow_run:
    workflows: 
      - "Python Flask App Build"
    types: completed
jobs:
  deploy_job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6.0.2
        with: 
          sparse-checkout: k8s
      - name: download artifact
        uses: actions/download-artifact@v4
        with:
          name: image-tag
          path: artifact
      - name: check image tag
        run: cat artifact/image-tag.txt 
      # - name: login to azure
      #   uses: Azure/login@v2.3.0
      # - name: install kubelogin
      #   uses: Azure/use-kubelogin@v1
      #   with:
      #     kubelogin-version: 'v0.1.4'
      # - name: set aks context
      #   uses: azure/aks-set-context@v4
      #   with:
      #     resource-group: myrg1
      #     cluster-name: myaks
      #     admin: 'false'
      #     use-kubelogin: 'true'
      # - name: deploy to aks
      #   uses: Azure/k8s-deploy@v4.9
      #   with:
      #     images: 
      #     manifests: k8s/python-app/deployment.yaml
      #     timeout: 30s
            
        
            
    
